---
apiVersion: v1
kind: Service
metadata:
  name: starrocksapp-starrocks-svc
spec:
  type: NodePort
  selector:
    app: starrocksapp-starrocks
  ports:
  - name: port9030
    protocol: TCP
    port: 9030
    targetPort: 9030
    nodePort: 59031
  - name: port8030
    protocol: TCP
    port: 8030
    targetPort: 8030
    nodePort: 58031
  - name: port8040
    protocol: TCP
    port: 8040
    targetPort: 8040
    nodePort: 58041
